### ISSUE TITLE
Provide a guide for how to self host Table Slayer

### ISSUE THREAD

**Issue by snide** [Siege-Perilous/tableslayer#243]
Right now Table Slayer requires at minimum a Turso, a Resend and a Cloudflare account. The DB needs to be migrated when first run. Likely some of this can be automated and managing through a simple bootstrap script.

**Comment by TrueOsiris** [comment]
Hey snide, thanks for this awesome project.

To fully selfhost with libsql, I created [this fork](https://github.com/TrueOsiris/tableslayer), and [an image on the docker hub](https://hub.docker.com/repository/docker/trueosiris/tableslayer/general).

To get it running, I had make a few changes.
Turbo shouldn't update on building, only on running the container.
Therefore we build with a dummy database file.

### override the default entrypoint in thhe Dockerfile (Web)
``` dockerfile
...
CMD ["./docker-entrypoint.sh"]
```

### docker-entrypoint.sh

``` bash
#!/bin/sh
set -e

echo "Running database migrations..."
pnpm run migrate

echo "Starting web app..."
exec node build
```

### turbo.json

``` json 
{
  "$schema": "https://turbo.build/schema.json",
  "tasks": {
    "web#migrate": {
      "outputs": [],
      "env": ["TURSO_APP_DB_URL", "TURSO_APP_DB_AUTH_TOKEN"]
    },
    "build": {
      "dependsOn": ["^build"],
      "inputs": ["$TURBO_DEFAULT", ".env*"],
      "outputs": [".svelte-kit/**"]
    },
    "web#build": {
      "dependsOn": ["^build"],
      "env": [
        "ENV_NAME",
        "GITHUB_PR_NUMBER",
        "TURSO_API_TOKEN",
        "TURSO_APP_DB_URL",
        "TURSO_APP_DB_AUTH_TOKEN",
        "RESEND_TOKEN",
        "RESEND_AUDIENCE_ID",
        "DEV_EMAIL",
        "BASE_URL",
        "CLOUDFLARE_ACCOUNT_ID",
        "CLOUDFLARE_R2_ACCESS_KEY",
        "CLOUDFLARE_R2_SECRET_KEY",
        "CLOUDFLARE_R2_BUCKET_NAME",
        "SENTRY_DSN",
        "SENTRY_AUTH_TOKEN",
        "BODY_SIZE_LIMIT",
        "STRIPE_SECRET_KEY",
        "STRIPE_WEBHOOK_KEY",
        "STRIPE_LIFETIME_ID",
        "STRIPE_YEARLY_ID",
        "STRIPE_PRICE_ID_MONTHLY",
        "STRIPE_PRICE_ID_YEARLY",
        "STRIPE_PRICE_ID_LIFETIME",
        "STRIPE_WEBHOOK_KEY",
        "STRIPE_API_KEY"
      ],
      "outputs": [".svelte-kit/**"]
    },
    "web#start": {
      "env": [
        "ENV_NAME",
        "GITHUB_PR_NUMBER",
        "TURSO_API_TOKEN",
        "TURSO_APP_DB_URL",
        "TURSO_APP_DB_AUTH_TOKEN",
        "RESEND_TOKEN",
        "RESEND_AUDIENCE_ID",
        "DEV_EMAIL",
        "BASE_URL",
        "CLOUDFLARE_ACCOUNT_ID",
        "CLOUDFLARE_R2_ACCESS_KEY",
        "CLOUDFLARE_R2_SECRET_KEY",
        "CLOUDFLARE_R2_BUCKET_NAME",
        "SENTRY_DSN",
        "SENTRY_AUTH_TOKEN",
        "BODY_SIZE_LIMIT",
        "STRIPE_SECRET_KEY",
        "STRIPE_WEBHOOK_KEY",
        "STRIPE_LIFETIME_ID",
        "STRIPE_YEARLY_ID",
        "STRIPE_PRICE_ID_MONTHLY",
        "STRIPE_PRICE_ID_YEARLY",
        "STRIPE_PRICE_ID_LIFETIME",
        "STRIPE_WEBHOOK_KEY",
        "STRIPE_API_KEY"
      ],
      "persistent": true,
      "cache": false
    },
    "docs#start": {
      "env": ["BASE_URL"],
      "persistent": true,
      "cache": false
    },
    "docs#build": {
      "env": ["BASE_URL"],
      "outputs": [".svelte-kit/**"]
    },
    "tsc": {
      "dependsOn": ["^tsc"],
      "outputs": []
    },
    "check": {
      "dependsOn": ["^check"],
      "outputs": []
    },
    "lint": {},
    "test": {
      "dependsOn": ["^build"]
    },
    "dev": {
      "cache": false,
      "persistent": true
    },
    "dev:party": {
      "cache": false,
      "persistent": true
    }
  }
}
```

and I created 2 docker-compose.yml's.

### docker compose with building:

``` yaml
services:
  db:
    image: ghcr.io/tursodatabase/libsql-server:latest
    platform: linux/amd64
    environment:
      - SQLD_NODE=primary
    volumes:
      - libsql-data:/var/lib/libsql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      TURSO_APP_DB_URL: "libsql://db:8080?tls=0"
      TURSO_APP_DB_AUTH_TOKEN: "devtoken" 
      ENV_NAME: "development"
      BASE_URL: "http://localhost:3000"
      BODY_SIZE_LIMIT: "20M"
    ports:
      - "3000:3000"

volumes:
  libsql-data:
```


### Fully running docker compose file with pre-build docker image:

``` yaml
services:
  db:
    image: ghcr.io/tursodatabase/libsql-server:latest
    platform: linux/amd64
    environment:
      - SQLD_NODE=primary
    volumes:
      - libsql-data:/var/lib/libsql

  web:
    image: trueosiris/tableslayer:latest
    depends_on:
      - db
    environment:
      TURSO_APP_DB_URL: "libsql://db:8080?tls=0"
      TURSO_APP_DB_AUTH_TOKEN: "devtoken" 
      ENV_NAME: "development"
      BASE_URL: "http://localhost:3000"
      BODY_SIZE_LIMIT: "20M"

    ports:
      - "3000:3000"

volumes:
  libsql-data:
```
